### ISSUE TITLE
Summary: Satisfactory

### ISSUE THREAD

**Issue by jzhu01** [gkdrumm/prj-rev-bwfs-dasmoto#5]
Great job on this project - I really loved your use of divs, as well as your implementation of classes on the spans. In terms of improvement, I recommend removing the font-weight bold on the h1, h2, and h3, as well as selecting all text HTML elements and applying the font-family once.

If you’re in the mood for a challenge, I would look into adding more items under each section and finding a nice way to lay them out. Here's a link to get you started - https://www.w3schools.com/css/css_rwd_grid.asp. Feel free to reach out and let us know if you have any questions, good luck!

**Comment by gkdrumm** [comment]
Thank You for the feedback! I love to hear praise as well as constructive criticism. I constantly strive to increase my knowledge & simplify my code. I've always been self taught & have few friends locally that operate on my level & frankly electronic social networking is appalling to me, so it has been difficult to find peers. I have been a carpenter/re-modeler most of my life & have decided I need a change & am wasting myself on something that should have been a hobby not career. So, here I am @ CodeAcademy & loving it. 
Thanks again,
 Greg
